Newsfeed/urls.py
from django.urls import path
from .views import ( NewsfeedListView,
NewsfeedDeleteView,
NewsfeedUpdateView,
NewsfeedDetailView,
NewsfeedCreateView,
test )
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf import settings

# newsfeed/
urlpatterns = [
    path('new/', NewsfeedCreateView.as_view(), name='newsfeed_new'), # new

    path('detail/<int:pk>/', NewsfeedDetailView.as_view(), name='newsfeed_detail'),

    path('<int:pk>/edit/',
        NewsfeedUpdateView.as_view(), name='newsfeed_edit'),
  
    path('<int:pk>/delete/',
        NewsfeedDeleteView.as_view(), name='newsfeed_delete'),
   
    path('list', NewsfeedListView.as_view(), name='newsfeed_list'),

    # path('comment', CommentView.as_view(), name='comment'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogDetailView, BlogCreateView,BlogUpdateView

urlpatterns = [
    path('blog/<int:pk>/edit/',
         BlogUpdateView.as_view(), name='blog_edit'), 
    path('mainblog/',BlogListView.as_view(),name= 'mainblog'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('newpost/',BlogCreateView.as_view(),name= 'new_post'),
]

sot_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from Newsfeed.views import test

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')), # new
    path('acha_bs', test.as_view()),
    path('users/', include('django.contrib.auth.urls')),
    path('newsfeed/', include('Newsfeed.urls')),
    
    
    
     
    
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Newsfeed/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
class Newsfeed(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images')
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
    get_user_model(),
    on_delete=models.CASCADE,
)
def __str__(self):
    return self.title
    
def get_absolute_url(self):
    return reverse('comment_detail', args=[str(self.id)])



class Comment(models.Model): # new
    Newsfeed = models.ForeignKey(
        Newsfeed,
        on_delete=models.CASCADE,
        related_name='comment',
    )
    comment = models.TextField(max_length=140)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('newsfeed_list')

Newsfeed/forms.py
from django.forms import ModelForm
from django import forms
from Newsfeed.models import Comment

class CommentForm(ModelForm):

    # comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 40, 'cols': 40}))

    class Meta:
        model = Comment
        fields = ['comment']

Newsfeed/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied 
from django.views.generic import ListView,DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView, FormView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy
from .models import Newsfeed, Comment
# from .forms import *
from .forms import CommentForm

class NewsfeedListView(LoginRequiredMixin, ListView):
    model = Newsfeed
    template_name = 'newsfeed/newsfeed_list.html'
    login_url = 'login'

class NewsfeedDetailView(LoginRequiredMixin, TemplateView): # new
   template_name = 'newsfeed/newsfeed_detail.html'

   def get_context_data(self, *args, **kwargs):
      context = super().get_context_data(**kwargs)
      commentform = CommentForm()
      id = kwargs['pk']
      newsfeed = Newsfeed.objects.get(id=id)
      comment = newsfeed.comment.all()
      # print(id)
      context = {'newsfeed':newsfeed , 'commentform':commentform, 'comments':comment}
      return context

   def post(self, request, pk):
      commentform = CommentForm(request.POST)
      if commentform.is_valid():
         commentfield = commentform.cleaned_data['comment']
         # newsfeedfield = commentform.cleaned_data['Newsfeed']
         save_comment = Comment(Newsfeed_id=pk, comment=commentfield, author_id=self.request.user.id)
         save_comment.save()         
         return HttpResponseRedirect('/')



class NewsfeedUpdateView(LoginRequiredMixin, UpdateView): # new
   model = Newsfeed
   fields = ('title', 'body','image',)
   template_name = 'newsfeed/newsfeed_edit.html'
   success_url = reverse_lazy('newsfeed_list')
   login_url = 'login'

   def dispatch(self, request, *args, **kwargs): # new
      obj = self.get_object()
      if obj.author != self.request.user:
         raise PermissionDenied
      return super().dispatch(request, *args, **kwargs)

class NewsfeedDeleteView(LoginRequiredMixin, DeleteView): # new
    model = Newsfeed
    template_name = 'newsfeed/newsfeed_delete.html'
    login_url = 'login'

    def dispatch(self, request, *args, **kwargs): # new
      obj = self.get_object()
      if obj.author != self.request.user:
         raise PermissionDenied
      return super().dispatch(request, *args, **kwargs)

class NewsfeedCreateView(LoginRequiredMixin, CreateView):
   model= Newsfeed
   template_name = 'newsfeed/newsfeed_new.html'
   fields = ('title', 'body','image')
   success_url = reverse_lazy('newsfeed_list')
   login_url = 'login'

   def form_valid(self, form): # new
      form.instance.author = self.request.user
      return super().form_valid(form)

class test(TemplateView): 

    template_name = "home/test.html" 

templates/newsfeed/comments.html
{% extends 'base.html' %} {% block content %}

<h3>hey ppl you guys can give your feedback here or if you want any query regarding our products le us know :)
    <h4>Feel free to contact us or comment here</h4>
</h3>

{% endblock content%}

templates/newsfeed/newsfeed_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ newsfeed.title }}"?</p>
    <button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/newsfeed/newsfeed_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
<div class="row">
<div class="col-lg-12">

    <!-- Title -->
    <h1 class="mt-4">{{ newsfeed.title | capfirst }}</h1>

    <!-- Author -->
    <p class="lead">
      by
      <a href="#">{{ newsfeed.author | capfirst }}</a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p>Posted on {{ newsfeed.date }}</p>

    <hr>

    <!-- Preview Image -->
    <div class="d-flex justify-content-center ">
        <img class="img-fluid rounded " src="{{ MEDIA_URL }}{{ newsfeed.image.url }}" alt="" style="object-fit: cover;
        width: 100%;
        height: 250px;">
    </div>


    <hr>

    <!-- Post Content -->
    <p class="lead">{{ newsfeed.body }}</p>

    <hr>

    <!-- Comments Form -->
    <div class="card my-4">
      <h4 class="card-header">Leave a Comment:</h4>
      <div class="card-body">
        <form method="POST">
            {% csrf_token %} 
            
          <div class="form-group">
            <textarea name="comment" rows="5" required="" id="id_comment" style="width: -webkit-fill-available;" ></textarea>   
          </div>
          <button type="submit" class="btn btn-info">Submit</button>
        </form>
      </div>
    </div>

    <!-- Single Comment -->
    {% for comment in comments %}
    <div class="media mb-4">
 
      <img class="d-flex mr-3 rounded-circle" src="https://bootdey.com/img/Content/user_1.jpg" 
      style="width: 50px;
      height: 50px;
      background-position: 50% 50%;
      background-repeat: no-repeat;
      background-size: cover;" alt="">

      <div class="media-body">
        
        <h4 class="mt-0">{{ comment.author | capfirst }}</h4>
        <p>{{ comment }}</p>   
     
    </div>
    
    </div>
    {% endfor %}

    <!-- Comment with nested comments -->


  </div>
  
</div>
</div>



{% endblock content %}

templates/newsfeed/newsfeed_edit.html
{% extends 'base.html' %} {% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %} {{ form.as_p }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/newsfeed/newsfeed_list.html
{% extends 'base.html' %} {% load static %} {% block title %}Articles{% endblock title %} {% block content %}


<div class="container my-5">

    {% for newsfeed in object_list %}
    <a href="{% url 'newsfeed_detail' newsfeed.pk %}">
        <div class="card mb-3">
            <div class="card-header">


                <span class="text-muted">by {{ newsfeed.author | capfirst }} |
         {{ newsfeed.date }}</span>

            </div>
            <div class="card-body" style="font-size: larger;">
                
                    <h2>{{ newsfeed.title | capfirst }}</h2>
                    <img src="{{ MEDIA_URL }}{{ newsfeed.image.url }}" alt="img" style="object-fit: cover;
                    width: 100%;
                    height: 250px;">

              
                
                <!-- Changes start here! -->

            </div>


        </div>
    </a>
    {% endfor %}
</div>


<br /> {% endblock content %}

templates/newsfeed/newsfeed_new.html
{% extends 'base.html' %} {% block content %}
<h1>New comment</h1>
<form action="" method="post">{% csrf_token %} {{ form.as_p }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
</form>
{% endblock content %}